---
title: "Portfolio Management"
author: "Group A"
date: "2023-04-05"
output: pdf_document
---

```{r, include=FALSE}
# Package names
packages <- c("ggplot2","reshape2", "readxl", "dplyr", "tidyr", "alphavantager", "httr","jsonlite","tidyverse","pracma","quantmod","tidyquant","corrplot","ggfortify"
              , "GGally","patchwork","factoextra")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```



```{r}

# Define the stocks in the portfolio
symbols<- c("AAPL","MSFT","AMZN","GOOGL","TSLA")

```

```{r,  message=FALSE}
# Retrieve the stock data of Apple, Microsoft, Amazon, Google, and Tesla
# from alpha vantage using an api key. The data collected is taken from last 20 
# years till today.

av_api_key("UPN4ARLW17K30CVM")

stocks <- list()

for (symbol in symbols) {
  data<-  av_get(
    symbol = symbol, 
    av_fun = "TIME_SERIES_MONTHLY_ADJUSTED", 
    av_outputsize = "full",
    parse="text" )
  
  stock_data<- data.frame(Date =data$timestamp,
                          Symbol=symbol,
                          Open =data$open,
                          High =data$high,
                          Low = data$low,
                          Close =  data$close,
                          Adjusted_close =data$adjusted_close,
                          Volume =  data$volume
                          )
   
   
   stocks<-rbind(stocks,stock_data)
   stock_data<- NULL
  
}
stock_returns<- stocks[rev(1:nrow(stocks)),]

```


```{r}
# Visualizations

# Create a time series plot of the monthly returns of different stocks to understand 
# the trends in closing price

 stock_returns %>% ggplot( aes(x = Date, y = Close , color = Symbol)) + geom_line() +
  labs(title = "Monthly Returns of Stocks", x = "Date", y = "Monthly closing price") + 
  facet_wrap(~Symbol) +theme_bw()


# Create scatterplot matrix
 
                              
# Coorelation matrix
corr_mat <- stock_returns %>% select(-Date,-Symbol) %>% cor
corr_mat

 
# Analyse the relation among open,high,low,close and adjusted price
corrplot(corr_mat,method = "number", type="full",title = "")

# Create a heat map of the correlation coefficients
heatmap( corr_mat, Colv = NA, Rowv = NA, scale="column")

# Create a box plot of the stock prices for each stock

 stock_returns %>% ggplot(aes(x=Date,y= Close,color= Symbol)) + geom_boxplot() +theme_bw()
 
```


```{r}

# Standardizing the market returns

standardized_returns<- stock_returns %>% select(-Date,-Symbol) %>%  as.matrix() %>% 
  scale(scale = TRUE, center = TRUE) 


# Applying pca on the standardized returns of the stocks
pca <- prcomp( standardized_returns)
pca

# Summary of the principal components

summary(pca)

# Computed 
# map_dfc(1:6, ~pca$rotation[, .] * sqrt(pca$sdev ^ 2)[.])


```

```{r}
# Plotting principal components against the amount of variance explained by them

fviz_screeplot(pca, addlabels = TRUE, choice = "variance")


# Create loading plot

autoplot(pca, data =  stock_returns, colour = 'Symbol',
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 4,) 

# This will create a scatter plot of the scores of each stock on the first two principal components, with the name of each stock labeled


# Create PCA biplot

pcaDat <- get_pca(pca)
fviz_pca_biplot(pca, label = "var")

# Create Variable loadings plot to represent the correlation of each of the variables with each principal component

fviz_pca_var(pca)

```


```{r}
# Building pca model

# Extract the loadings of each stock on the principal components

loadings <- pca$rotation
loading_data <- data.frame(Features = colnames(standardized_returns ), 
                           PC1 = loadings[,1], 
                           PC2 = loadings[,2])

# Plot the loading plot to visualize the relationship between the stocks and the principal components

ggplot(loading_data, aes(x = PC1, y = PC2,color= Features)) + 
  geom_point() +  
  geom_text(aes(label =  Features), hjust = -0.2, vjust = -0.2) + 
  labs(x = "PC1", y = "PC2") + 
  ggtitle("Mapping ") + theme_bw()

```